runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: lmdsqtbox.app
  secure: always

libraries:
- name: pycrypto
  version: "2.6"
